include $(CLEAR_VARS)
LOCAL_MODULE := MagiskManager
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := MagiskManager/MagiskManager.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
